### ISSUE TITLE
new features

### ISSUE THREAD

**Issue by lzto** [ririhedou/dr_droid#2]
Hi,
I tested this tool and it is very helpful. I wonder could you add some new features (e.g., hardware features from Drebin) to make this tool more powerful?
https://www.tu-braunschweig.de/Medien-DB/sec/pubs/2014-ndss.pdf

Best,

**Comment by ririhedou** [comment]
Thanks for your feedback. I go through this article and think it is not hard to realize these features.
But after updating new features, we may have to re-train the classifier. I will update new code in a separate file ASAP.
